# Configuración para herramientas de formato y linting

# Para flake8 (usaremos setup.cfg o .flake8 para la configuración)
# [tool.flake8] no es compatible con pyproject.toml estándar

# Para black
[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | venv
  | __pycache__
  | \.pytest_cache
)/
'''

# Para isort
[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["app"]
skip = ["venv", "__pycache__"]